# Generated by Django 5.0.7 on 2024-08-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='possible_answers_json',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer_log_json',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='flashcard_data_json',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='possible_answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='flashcard_data',
            field=models.JSONField(default=dict),
        ),
    ]
